# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b5ec3f8797082cb2467973671b91d1c6c10f1809f0326058e3dcd8434b5c22a3754791bdab64858435dcd5c73db083596814941a4318f5c37869d95e4ffb5d9

test:
  secret_key_base: 045cd0023727d3987734c01fd0b78ae7544634a1f8e7af5ade9fbb9e6bbcca250fd2c8f080c7fe5e05026d96ccb01bf34dd91292c2129a83d09bf00c41e3dd26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
